### ISSUE TITLE
PDK5 sites: Stay with the whitelist approach or build something that detects CDN loads? 

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-addon#43]
@wisniewskit can you send in your POC as a PR, or link it here?

It would be good to try to find some other sites using PDK5 (perhaps with HTTPArchive or similar?), and do testing on say 5 of them. If it seems OK, let's go the CDN route.

**Comment by wisniewskit** [comment]
Sure, here's a link to the XPI of my POC: https://thomas.tanrei.ca/moz/pdk5fix.xpi

All that's needed to add to its list of CDNs is to find the URL variant that accesses the tdPdk.js script, and wildcard it as seen in the background.js. It might be worth testing PDK4 and lower too, if we ever find a site still using it (a UA-spoof might work fine for lower versions too).

**Comment by miketaylr** [comment]
I used BigQuery + HTTP Archive to find sites in their latest million or so pages mobile run:

https://docs.google.com/spreadsheets/d/1GTlqPMvhe5UjTL_FpvLKTziLg_Qosplw06OgsghQ2z4/edit#gid=1582508588

Just 47 sites (matching against `pdk[.-](player|theplatform).+5`, should be enough for us to test and have some confidence.

**Comment by wisniewskit** [comment]
It turns out that simply spoofing the UA may be a bit much; Cooking Channel TV's site ran into long delays loading the page, for instance. As such I've decided to just edit the incoming scripts to apply the fix I suggested in https://webcompat.com/issues/8410 (basically, changing the string `VideoContextChromeAndroid` to `VideoContextAndroid` in the relevant script).

This approach seems to be working fine on at least these sites:
- CNBC (https://webcompat.com/issues/8410)
- Rotten Tomatoes (https://webcompat.com/issues/14308)
- Cooking Channel TV (https://webcompat.com/issues/25887)
- National Geographic (https://webcompat.com/issues/24547)

In addition, it works fine on a version of PDK (5.9.6.536014) which doesn't need the fix and already works on Fennec (https://webcompat.com/issues/2351 is working now). It also avoids doing any UA spoofing, which is a likely win for metrics.
