### ISSUE TITLE
Custom overrides

### ISSUE THREAD

**Issue by cromefire** [mozilla/webcompat-addon#60]
I don't know if this is the correct issue tracker, so correct me if I'm wrong.

It would be cool if there was a way to inject custom Scripts/CSS into custom pages (in that case even a ua override would be sufficient), because I've a problem with a page of a network device, but I already know how to fix it.

**Comment by denschub** [comment]
Hi @cromefire, and thanks for getting in touch! Unfortunately, I'm 99% sure we'll never offer customization besides turning things off because that's not really our goal. We use this addon to fix site issues when we have received a report and decided that we want to fix that immediately. These overrides are never alone, they always are accompanied by us trying to get the site's team involved, or us trying to fix the underlying Firefox issue. Ultimately, this addon should only carry temporary workarounds until a *proper* solution is established. Enabling any sort of custom overrides would really violate that model.

Also, this isn't even a proper addon - it's not available on addons.mozilla.org, it's not listed on `about:addons`, and you'll also have trouble building and installing it yourself because it depends on some Gecko-native functions. This project uses some addon-mechanics so that we're able to be more flexible in re-using code and shipping updates, but it's absolutely not the kind of addon you'd expect when talking about Firefox addons. :)

However, I have two things to add:

* If you find a broken website, please go ahead and report that on https://webcompat.com/ - these are the reports Mozilla's WebCompat team uses to discover broken websites, and those are also the basis for interventions that get rolled out. For things like network devices, reporting those bugs is a bit tricky because we'd have a hard time reproducing it, but if you can boil the issue down to a test case that we can have a look at, someone will absolutely have a look at your report.
* Ultimately, most of the actual overriding magic happens in basic webextension content scripts. So actually, you don't even need this addon as a carrier. If you know how to fix an issue you have, [check out the WebExtension documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions) and build your own addon!

**Comment by cromefire** [comment]
Okay

> If you find a broken website, please go ahead and report that on https://webcompat.com/

The problem is that this affects a local webinterface so this is not viable

**Comment by denschub** [comment]
You could give it a try anyway. If you can share a screenshot and the solution you found to fix it, we might be able to reverse-engineer the issue. :)

**Comment by cromefire** [comment]
It's just broken CSS but did not yet reach out to the manufacturer
