### ISSUE TITLE
addon doesn't work when loaded with web-ext

### ISSUE THREAD

**Issue by ksy36** [mozilla/webcompat-addon#68]
When trying to load the addon with web-ext, none of the overrides work and there is the following error in the console:

```
1563809264475	addons.xpi	WARN	Failed to parse recommendation: TypeError: NetworkError when attempting to fetch resource. No traceback available
1563809264489	addons.xpi	WARN	Addon with ID webcompat@mozilla.org already installed, older version will be disabled
TypeError: browser.aboutConfigPrefs is undefined
```

which points to `src/lib/injections.js` and this function: 
```
  bootup() {
    browser.aboutConfigPrefs.onPrefChange.addListener(() => {
      this.checkInjectionPref();
    }, this.INJECTION_PREF);
    this.checkInjectionPref();
  }
```

**Comment by denschub** [comment]
Hmm. Looks like there are several things wrong with `about:compat` and temporary addons (doesn't matter if via `about:debugging` or `web-ext`). Even in a profile with all the right prefs set, we run into weird issues.

For now,  alocal build is probably the way to go testing, but I'll chat with some devtools people who might have an idea on why temporary addons seem to be unable to run the experimental APIs...

**Comment by wisniewskit** [comment]
After chatting with folks, it seems like Fennec nightlies have not honored the `extension.legacy.enabled` pref since around the time the ESR was split off. I wouldn't be surprised if this is related, so I'll ping around to make sure.

**Comment by denschub** [comment]
This is somewhat known, expected, and can't be fixed, unfortunately. If you have to test in Fennec, there is a Mozilla-internal workaround, so you have two options:

* Build your own Fennec that includes the new exported sources (either build on your machine, or push to try)
* Ping either me or @ksy36 to get insight into how you could make `web-ext` work with Fennec release build.

Since there isn't anything we can do here, let's close this.
